### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by xukai92** [JuliaEarth/DensityRatioEstimation.jl#17]
Shall we stick to some style guides? Personally, I follow Julia's https://docs.julialang.org/en/v1/ and Turing/Invenia's https://turing.ml/dev/docs/contributing/style-guide.

**Comment by juliohm** [comment]
I think most Julia packages follow a style guide implicitly :) The only thing that I think is different in my projects is the 2 space indentation as opposed to 4 spaces. I think 4 spaces take a lot of space and Julia is clean enough, 2 spaces are visible enough. But we can change that if you feel 4 spaces is better.

**Comment by xukai92** [comment]
> I think most Julia packages follow a style guide implicitly :)

Yes. But having a guide for reference can be useful when there are some style inconsistency.

> But we can change that if you feel 4 spaces is better.

I prefer 4 spaces as most of the Julia packages I'm involved in follow this.

**Comment by juliohm** [comment]
> I prefer 4 spaces as most of the Julia packages I'm involved in follow this.

Feel free to change to 4 spaces :) I can do that as well in subsequent PRs if you prefer.

**Comment by juliohm** [comment]
I think the style guide is important, let's iterate more and decide a good compromise.

- I have personal preference for 2 spaces indentation as it makes code short in limited column size view, but I am fine with 4 spaces if you prefer it. Many packages use 4 spaces.

- The `return` keyword is not needed in my opinion. Thanks for sharing the discussion on Google Groups, very interesting.

We can add more style details to this thread as they appear.

**Comment by xukai92** [comment]
Thanks Júlio. Another thing is about spaces between operators and commas. I think we should always add spaces for them, but I have two personal expections.

1. For `^`, I prefer `a^2` over `a ^ 2`
2. For array indexing, I prefer `x[1,2,3]` over `x[1, 2, 3]`. 

How do you think?

**Comment by juliohm** [comment]
Like it, it is very clean. :+1:

**Comment by juliohm** [comment]
- For literals with more than 4 digits, we add underscores, e.g. 1_000.

**Comment by juliohm** [comment]
Should we perhaps convert this issue into a CONTRIBUTING.md file with a style section?

**Comment by xukai92** [comment]
Yes sounds good to me. What else should we include there?

**Comment by juliohm** [comment]
Sorry for the delay to reply. I've just re-encountered this issue we opened a long time ago... I think we are pretty aligned with the adopted style. :ok_hand: Let's close this issue for now and reconsider a CONTRIBUTING.md file after people start contributing. It is pretty calm around here so far.
