### ISSUE TITLE
Add LCV constructor with varargs

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/DensityRatioEstimation.jl#27]
It would be nice to construct `LCV` with varargs.

**Comment by xukai92** [comment]
Can you explain with an example?

**Comment by juliohm** [comment]
Right now we need to type:

```julia
LCV((b=[100,50],\sigma=[1.,2.]))
```

Perhaps we should be able to type instead:

```julia
LCV(b=[100,50], \sigma=[1.,2.], nfolds=10)
```

**Comment by juliohm** [comment]
I will close this issue for now and think more carefully about this need. I think the issue is more profound about how to hyperparameter tune these density ratio estimators, it is also connected to that issue of finding the median sigma as a heuristic.
