### ISSUE TITLE
Tests fail with Convex.jl backend

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/DensityRatioEstimation.jl#40]
By any chance can you take a look at the convex.jl implementations and update them to the latest Convex.jl release? It should be a one line change.

I am having trouble testing locally because of some artifact download errors, but we need to address this issue soon and release a new version. If you can take a look, that would be great.

**Comment by juliohm** [comment]
It is unfortunate that Requires.jl doesn't allow compat versions. We will be constantly falling into this issue whenever an optimization backend has breaking changes.

**Comment by juliohm** [comment]
Hopefully this will be supported by future releases of Pkg.jl: https://github.com/JuliaLang/Pkg.jl/issues/1285

**Comment by juliohm** [comment]
Fixed on master.

**Comment by xukai92** [comment]
Thanks for the fix!
