### ISSUE TITLE
Unexpected results when using v0.4.3

### ISSUE THREAD

**Issue by RTbecard** [JuliaEarth/DensityRatioEstimation.jl#43]
First off, great package!  I'm using this to calculate density ratios between successive posterior distributions in an Approximate Bayesian Computation sequential Monte Carlo algorithm to generate adaptive distance thresholds.

I was getting some unexpected output which was really messing up my analysis... after playing around, I noticed that when I downgrade your package from 0.4.3 to 0.4.1 and restart my REPL, I then get the output I expect.   See MWE below:

 ```julia
using DensityRatioEstimation
using Distributions
using StatsBase
using Optim

# Make multivariate sampling distributions
d1 = MvNormal([0, 1], [3 0; 0 3])
d2 = MvNormal([0, 1], [1 0; 0 1])
# Calculate true maximum density ratio values
t1 = pdf(d2, [0, 1])/pdf(d1, [0, 1])
t2 = pdf(d1, [0, 1])/pdf(d1, [0, 1])
# Sample from distribution
s1 = rand(d1, 1000)
s2 = rand(d1, 1000)
s3 = rand(d2, 1000)
N = size(s1)[2]
# Convert matricies to nested arrays
s1 = [ s1[:, i]  for i in 1:N ]
s2 = [ s2[:, i]  for i in 1:N ]
s3 = [ s3[:, i]  for i in 1:N ]
# Get density ratio functions
r1 = densratiofunc(s1, s2, KLIEP())
r2 = densratiofunc(s3, s2, KLIEP())
# Estimate the maximum density ratio
min1 = optimize(x -> -r1(x), [0., 0.])
min2 = optimize(x -> -r2(x), [0., 0.])

# Show estimated maximum ratio
println("""
        Estimated maximum density ratios from DensityRatioEstimation.jl
        Sampled from same dist: $(-min1.minimum)
        Sampled from different dist: $(-min2.minimum)
        ---
        Expected values (from pdf functions)
        Same dist: $t2
        Different dist: $t1
        """)
```
Heres my output when using 0.4.3
```text
Estimated maximum density ratios from DensityRatioEstimation.jl
Sampled from same dist: 1.5760503856890502
Sampled from different dist: 1.733492323940745
---
Expected values (from pdf functions)
Same dist: 1.0
Different dist: 3.0000000000000004
```
And now after I downgrate to 0.4.1

```text
Estimated maximum density ratios from DensityRatioEstimation.jl
Sampled from same dist: 1.7245805746578469
Sampled from different dist: 3.148675642517627
---
Expected values (from pdf functions)
Same dist: 1.0
Different dist: 3.0000000000000004
```

When using 0.4.1, the values for my maximum dens ratio between the different distributions always varies around the true value 3.... but when using 0.4.3 it seems to erroneously converge on ~1.77

The math behind this all is way over my head (I'm a biologist modelling fish movement), so its very possible I'm just not using these tools right and misunderstanding the concept of density ratios on some level.

**Comment by juliohm** [comment]
Thank you for reporting the issue @RTbecard , could you please share the diff between the two versions? We don't touch this package in a while so the issue may be in the dependencies. We use Require.jl so things break sometimes without us noticing unfortunately.

**Comment by juliohm** [comment]
It may actually be the default values for the parameters? https://github.com/JuliaEarth/DensityRatioEstimation.jl/compare/v0.4.1...v0.4.3

We changed the default to 10 samples instead of 20 and the default bandwidth from 1 to 2.

**Comment by RTbecard** [comment]
Thanks for the quick reply!  I'm swamped in an analysis right now... but I'll be back at this in two weeks to follow up and check if the problem on my machine is with package dependencies or the different default values as you suggested.

**Comment by juliohm** [comment]
I am closing this issue assuming the problem was with the defaults.
